"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { BirchIcon } from "@/components/icons/BirchIcons";
import { approveApplication, compileCoverLetterPdf, compilePdf, generateSuggestedMaterials, getHistory, getHistoryRecord, updateHistoryStatus } from "@/lib/api";
import { useLanguage } from "@/lib/language-context";

interface HistoryRecord { id: number; timestamp: string; job_title: string; company: string; match_score: number; ats_scores: { overall: number | null }; status: string; approval_status?: string; has_resume: boolean; has_cover_letter: boolean }
interface RecordDetail { resume_tex: string; cover_letter: string }
const STATUSES = ["suggested", "generated", "applied", "interview", "offer", "rejected"];
const LABELS = { suggested: { zh: "待审核", en: "Suggested" }, generated: { zh: "已生成", en: "Generated" }, applied: { zh: "已申请", en: "Applied" }, interview: { zh: "面试中", en: "Interview" }, offer: { zh: "Offer", en: "Offer" }, rejected: { zh: "已结束", en: "Closed" } } as const;

export default function ApplicationRecords({ limit }: { limit?: number }) {
  const { text, language } = useLanguage();
  const [records, setRecords] = useState<HistoryRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [expanded, setExpanded] = useState<number | null>(null); const [detail, setDetail] = useState<RecordDetail | null>(null); const [tab, setTab] = useState<"resume" | "cover">("resume"); const [busy, setBusy] = useState(false); const [actionBusy, setActionBusy] = useState<number | null>(null);

  const load = useCallback(async () => { setLoading(true); setError(""); try { const result = await getHistory(); setRecords(result.records ?? []); } catch (reason) { setError(reason instanceof Error ? reason.message : text("无法读取申请记录", "Could not load applications")); } finally { setLoading(false); } }, [text]);
  useEffect(() => { load(); }, [load]);

  async function open(recordId: number) { if (expanded === recordId) { setExpanded(null); setDetail(null); return; } setExpanded(recordId); setDetail(null); setTab("resume"); try { const result = await getHistoryRecord(recordId); setDetail({ resume_tex: result.record.resume_tex ?? "", cover_letter: result.record.cover_letter ?? "" }); } catch { setDetail({ resume_tex: "", cover_letter: "" }); } }
  async function changeStatus(recordId: number, status: string) { await updateHistoryStatus(recordId, status); setRecords((current) => current.map((record) => record.id === recordId ? { ...record, status } : record)); }
  async function generateMaterials(recordId: number) { setActionBusy(recordId); try { await generateSuggestedMaterials(recordId); await load(); } catch (reason) { alert(reason instanceof Error ? reason.message : text("材料生成失败", "Material generation failed")); } finally { setActionBusy(null); } }
  async function approve(recordId: number) { setActionBusy(recordId); try { await approveApplication(recordId); await load(); } catch (reason) { alert(reason instanceof Error ? reason.message : text("审批失败", "Approval failed")); } finally { setActionBusy(null); } }
  async function downloadPdf(record: HistoryRecord) { if (!detail) return; setBusy(true); try { const result = tab === "resume" ? await compilePdf(record.id) : await compileCoverLetterPdf(record.id); if (!result.ok) throw new Error(result.error || "PDF failed"); const bytes = Uint8Array.from(atob(result.pdf_base64), (char) => char.charCodeAt(0)); const url = URL.createObjectURL(new Blob([bytes], { type: "application/pdf" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${record.company}-${tab}.pdf`; anchor.click(); URL.revokeObjectURL(url); } catch (reason) { alert(reason instanceof Error ? reason.message : text("PDF 下载失败", "PDF download failed")); } finally { setBusy(false); } }

  if (loading) return <div className="h-40 animate-pulse rounded-[16px] bg-[rgba(30,26,20,0.05)]" />;
  if (error) return <div className="rounded-[16px] border border-[rgba(30,26,20,0.12)] bg-[#EBE2CC] p-8 text-center"><p className="text-sm">{error}</p><button onClick={load} className="secondary-button mt-4">{text("重试", "Try again")}</button></div>;
  const visible = limit ? records.slice(0, limit) : records;
  if (visible.length === 0) return <div className="rounded-[16px] border border-[rgba(30,26,20,0.12)] bg-[rgba(245,239,224,0.4)] p-10 text-center"><BirchIcon name="winter" size={38} className="mx-auto opacity-60" /><h3 className="mt-4 text-sm font-medium tracking-[0.1em]">{text("还没有申请记录", "No applications yet")}</h3><p className="mt-2 text-xs text-[#7A6A50]">{text("分析一个职位并生成第一份定制材料。", "Analyze a role and create your first tailored application.")}</p><Link href="/generate" className="primary-button mt-5">{text("生成材料", "Create application")}</Link></div>;

  return <div className="overflow-hidden rounded-[16px] border border-[rgba(30,26,20,0.12)] bg-[#F5EFE0]">{visible.map((record, index) => <div key={record.id} className={index ? "border-t border-[rgba(30,26,20,0.12)]" : ""}>
    <article className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:px-5"><button onClick={() => open(record.id)} className="flex min-w-0 flex-1 items-center gap-3 text-left"><span className="flex size-10 shrink-0 items-center justify-center rounded-[6px] bg-[#EBE2CC] text-sm">{record.company.charAt(0).toUpperCase()}</span><span className="min-w-0"><span className="block truncate text-sm font-medium tracking-[0.1em]">{record.job_title}</span><span className="mt-1 block truncate text-[10px] text-[#7A6A50]">{record.company} · {new Date(record.timestamp).toLocaleDateString(language === "zh" ? "zh-CN" : "en-CA")}</span></span></button><div className="flex flex-wrap items-center gap-3">{record.match_score > 0 && <span className="rounded-[6px] bg-[#EBE2CC] px-2 py-1 text-[10px] text-[#1E1A14]">{text("匹配", "Match")} {record.match_score}%</span>}{record.has_resume && record.ats_scores.overall != null && <span className="rounded-[6px] bg-[#1E1A14] px-2 py-1 text-[10px] text-[#F5EFE0]">ATS {record.ats_scores.overall}%</span>}{record.status === "suggested" && <button onClick={() => generateMaterials(record.id)} disabled={actionBusy === record.id} className="secondary-button min-h-9 py-1 text-[10px] disabled:opacity-50">{actionBusy === record.id ? text("生成中…", "Generating…") : text("生成材料", "Generate materials")}</button>}{record.approval_status === "ready" && <button onClick={() => approve(record.id)} disabled={actionBusy === record.id} className="secondary-button min-h-9 py-1 text-[10px] disabled:opacity-50">{text("批准材料", "Approve materials")}</button>}{record.approval_status === "approved" && <span className="text-[10px] text-[#7A6A50]">{text("已批准", "Approved")}</span>}<select value={record.status} onChange={(event) => changeStatus(record.id, event.target.value)} className="min-h-9 px-2 text-[10px]" aria-label={text("申请状态", "Application status")}>{STATUSES.map((status) => <option key={status} value={status}>{LABELS[status as keyof typeof LABELS][language]}</option>)}</select><button onClick={() => open(record.id)} className="flex size-9 items-center justify-center rounded-[6px] border border-[rgba(30,26,20,0.12)]" aria-label={text("查看文档", "View documents")}><BirchIcon name="bark" size={17} /></button></div></article>
    {expanded === record.id && <div className="border-t border-[rgba(30,26,20,0.12)] bg-[#EBE2CC] p-4 sm:p-5">{detail ? <><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><button onClick={() => setTab("resume")} className={`rounded-[6px] px-3 py-2 text-[10px] ${tab === "resume" ? "bg-[#1E1A14] text-[#F5EFE0]" : "bg-[#F5EFE0]"}`}>{text("简历", "Resume")}</button><button onClick={() => setTab("cover")} className={`rounded-[6px] px-3 py-2 text-[10px] ${tab === "cover" ? "bg-[#1E1A14] text-[#F5EFE0]" : "bg-[#F5EFE0]"}`}>{text("求职信", "Cover Letter")}</button></div><button onClick={() => downloadPdf(record)} disabled={busy || !(tab === "resume" ? detail.resume_tex : detail.cover_letter)} className="primary-button min-h-9 py-1 text-[10px] disabled:cursor-not-allowed disabled:opacity-50"><BirchIcon name="bark" size={14} />{busy ? text("生成中…", "Preparing…") : text("下载 PDF", "Download PDF")}</button></div><pre className="mt-4 max-h-80 overflow-auto whitespace-pre-wrap rounded-[6px] border border-[rgba(30,26,20,0.12)] bg-[#F5EFE0] p-4 font-mono text-[10px] leading-5 text-[#7A6A50]">{tab === "resume" ? detail.resume_tex || text("暂无简历内容", "No resume content") : detail.cover_letter || text("暂无求职信", "No cover letter")}</pre></> : <div className="h-32 animate-pulse rounded-[16px] bg-[rgba(30,26,20,0.05)]" />}</div>}
  </div>)}</div>;
}
