"use client";

import { ChangeEvent, FormEvent, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import Header from "@/components/Header";
import LanguageSwitch from "@/components/LanguageSwitch";
import { Section, WorkspacePage } from "@/components/workspace/WorkspaceUI";
import { useAuth } from "@/lib/auth-context";
import { useLanguage } from "@/lib/language-context";
import { changePassword, deleteAccount, exportAccount } from "@/lib/auth-api";
import { importWorkspace } from "@/lib/workspace-api";
import { useWorkspace } from "@/lib/workspace-context";
import type { WorkspaceData } from "@/lib/workspace-types";

export default function SettingsPage() {
  const { user } = useAuth(); const { text } = useLanguage(); const { refresh } = useWorkspace(); const router = useRouter();
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  async function passwordSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const next = String(data.get("new_password") ?? ""); if (next !== String(data.get("confirm_password") ?? "")) { setError(text("两次新密码不一致。", "New passwords do not match.")); return; } setBusy("password"); setError(""); try { await changePassword(String(data.get("current_password") ?? ""), next); form.reset(); setMessage(text("密码已更新。", "Password updated.")); } catch (reason) { setError(reason instanceof Error ? reason.message : "Password could not be changed"); } finally { setBusy(""); } }
  async function downloadExport() { setBusy("export"); setError(""); try { const data = await exportAccount(); const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `hua-workspace-${new Date().toLocaleDateString("en-CA")}.json`; anchor.click(); URL.revokeObjectURL(url); setMessage(text("数据导出已下载。", "Data export downloaded.")); } catch (reason) { setError(reason instanceof Error ? reason.message : "Export failed"); } finally { setBusy(""); } }
  async function uploadImport(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setBusy("import"); setError(""); try { const data = JSON.parse(await file.text()) as Partial<WorkspaceData>; await importWorkspace({ projects: data.projects ?? [], tasks: data.tasks ?? [], knowledge: data.knowledge ?? [] }); await refresh(); setMessage(text("项目、任务和知识已导入；重复 ID 已跳过。", "Projects, tasks, and knowledge imported; duplicate IDs were skipped.")); } catch (reason) { setError(reason instanceof Error ? reason.message : "Import failed"); } finally { setBusy(""); event.target.value = ""; } }
  async function removeAccount(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; if (!window.confirm(text("确定永久删除账户及所有数据？此操作无法撤销。", "Permanently delete your account and all data? This cannot be undone."))) return; setBusy("delete"); setError(""); try { await deleteAccount(String(new FormData(form).get("password") ?? "")); router.push("/login"); window.location.reload(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Account could not be deleted"); } finally { setBusy(""); } }
  return <><Header eyebrow={{ zh: "工作区设置", en: "WORKSPACE SETTINGS" }} title={{ zh: "设置", en: "Settings" }} subtitle={{ zh: "管理账户、偏好、数据边界和外部连接。", en: "Manage account, preferences, data boundaries, and connections." }} /><WorkspacePage>
    {message && <p className="rounded-[12px] border border-[rgba(30,26,20,0.12)] bg-[#F5EFE0] p-4 text-xs">{message}</p>}{error && <p className="rounded-[12px] bg-[#EBE2CC] p-4 text-xs">{error}</p>}
    <Section title={text("语言", "Language")} eyebrow={text("界面偏好", "Interface preference")}><div className="flex items-center justify-between gap-5 rounded-[16px] border border-[rgba(30,26,20,0.12)] bg-[#F5EFE0] p-5"><div><p className="text-sm font-medium tracking-[0.1em]">{text("界面语言", "Interface language")}</p><p className="mt-1 text-xs leading-5 text-[#7A6A50]">{text("选择会自动保存，并应用到整个工作区。", "Your choice is saved and applied across the workspace.")}</p></div><LanguageSwitch /></div></Section>
    <Section title={text("账户", "Account")} eyebrow={text("当前用户", "Current user")}><div className="rounded-[16px] border border-[rgba(30,26,20,0.12)] bg-[#F5EFE0] p-5"><p className="latin text-[10px] uppercase tracking-[0.28em] text-[#9A8468]">Email</p><p className="mt-2 text-sm">{user?.email}</p><p className="mt-4 text-xs leading-6 text-[#7A6A50]">{text("所有新建的 Project、Task 和 Knowledge 数据都绑定当前 user_id。", "Every new Project, Task, and Knowledge item is scoped to the current user_id.")}</p></div></Section>
    <Section title={text("修改密码", "Change password")} eyebrow={text("账户安全", "Account security")}><form onSubmit={passwordSubmit} className="grid gap-4 rounded-[16px] border border-[rgba(30,26,20,0.12)] bg-[#F5EFE0] p-5 sm:grid-cols-3"><label className="text-xs">{text("当前密码", "Current password")}<input name="current_password" type="password" required className="mt-1.5 min-h-11 w-full px-3" /></label><label className="text-xs">{text("新密码", "New password")}<input name="new_password" type="password" minLength={8} required className="mt-1.5 min-h-11 w-full px-3" /></label><label className="text-xs">{text("确认新密码", "Confirm new password")}<input name="confirm_password" type="password" minLength={8} required className="mt-1.5 min-h-11 w-full px-3" /></label><button disabled={busy === "password"} className="primary-button justify-self-start disabled:opacity-50">{busy === "password" ? text("更新中…", "Updating…") : text("更新密码", "Update password")}</button></form></Section>
    <Section title={text("数据导入与导出", "Import and export")} eyebrow={text("可携带数据", "Data portability")}><div className="flex flex-wrap gap-3 rounded-[16px] border border-[rgba(30,26,20,0.12)] bg-[#F5EFE0] p-5"><button onClick={() => void downloadExport()} disabled={busy === "export"} className="primary-button disabled:opacity-50">{text("下载完整导出", "Download full export")}</button><label className="secondary-button cursor-pointer">{busy === "import" ? text("导入中…", "Importing…") : text("导入工作区 JSON", "Import workspace JSON")}<input type="file" accept="application/json,.json" onChange={(event) => void uploadImport(event)} className="hidden" /></label><p className="w-full text-[10px] leading-5 text-[#7A6A50]">{text("完整导出包含账户内容但不包含密码或 OAuth 令牌；导入恢复项目、任务和知识。", "Full exports include account content but never passwords or OAuth tokens; imports restore projects, tasks, and knowledge.")}</p></div></Section>
    <Section title={text("工作区管理", "Workspace management")}><div className="grid gap-6 sm:grid-cols-2">{[{ href: "/profile", zh: "职业档案", en: "Career profile", detailZh: "管理职业经历和技能", detailEn: "Manage experience and skills" }, { href: "/integrations", zh: "集成与权限", en: "Integrations & permissions", detailZh: "连接外部工具并控制访问", detailEn: "Connect tools and control access" }].map((item) => <Link key={item.href} href={item.href} className="lift-card rounded-[16px] border border-[rgba(30,26,20,0.12)] bg-[#F5EFE0] p-5"><h3 className="text-sm font-medium tracking-[0.1em]">{text(item.zh, item.en)}</h3><p className="mt-2 text-xs text-[#7A6A50]">{text(item.detailZh, item.detailEn)}</p></Link>)}</div></Section>
    <div className="rounded-[16px] border border-[rgba(30,26,20,0.12)] bg-[#EBE2CC] p-5"><p className="text-xs font-medium tracking-[0.1em] text-[#1E1A14]">{text("数据适配层", "Data adapter")}</p><p className="mt-2 text-xs leading-6 text-[#7A6A50]">{text("Projects、Tasks、Knowledge、Documents 与智能功能均通过逐用户 FastAPI 数据层保存。旧浏览器数据会在首次加载时安全导入。", "Projects, Tasks, Knowledge, Documents, and intelligence features are stored through the per-user FastAPI data layer. Legacy browser data is safely imported on first load.")}</p></div>
    <Section title={text("删除账户", "Delete account")} eyebrow={text("危险操作", "Danger zone")}><form onSubmit={removeAccount} className="rounded-[16px] border border-[rgba(30,26,20,0.18)] bg-[#F5EFE0] p-5"><p className="text-xs leading-6 text-[#7A6A50]">{text("永久删除账户、职业记录、工作区内容、文档版本与集成信息。", "Permanently removes the account, career history, workspace content, document versions, and integrations.")}</p><div className="mt-4 flex flex-wrap gap-3"><input name="password" type="password" required placeholder={text("输入密码确认", "Enter password to confirm")} className="min-h-10 px-3 text-xs" /><button disabled={busy === "delete"} className="secondary-button text-[#1E1A14] disabled:opacity-50">{text("永久删除账户", "Delete account permanently")}</button></div></form></Section>
  </WorkspacePage></>;
}
