"use client";

import { FormEvent, useEffect, useState } from "react";
import Header from "@/components/Header";
import { CreatePanel, EmptyState, Section, StatusPill, WorkspacePage } from "@/components/workspace/WorkspaceUI";
import { AutomationRun, createAutomation, listAutomations, PlatformAutomation, runAutomation, updateAutomation } from "@/lib/platform-api";
import { useLanguage } from "@/lib/language-context";
import AutomationRunHistory from "@/components/automation/AutomationRunHistory";

export default function AutomationsPage() {
  const { text } = useLanguage(); const [items, setItems] = useState<PlatformAutomation[]>([]); const [runs, setRuns] = useState<AutomationRun[]>([]); const [creating, setCreating] = useState(false); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  async function load() { try { const data = await listAutomations(); setItems(data.automations); setRuns(data.runs); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Automations could not be loaded"); } }
  useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const kind = String(form.get("kind")); await createAutomation({ name: String(form.get("name")), kind, schedule: String(form.get("schedule") ?? "manual"), max_retries: Number(form.get("max_retries") ?? 2), config: kind === "job_search" ? { query: String(form.get("query") ?? "").trim() || String(form.get("name")), location: String(form.get("location") ?? "canada"), sources: ["indeed", "adzuna"], min_match_score: Number(form.get("min_match_score") ?? 60), generate_materials: form.get("generate_materials") === "on", max_generate: Number(form.get("max_generate") ?? 1), timezone: Intl.DateTimeFormat().resolvedOptions().timeZone } : { timezone: Intl.DateTimeFormat().resolvedOptions().timeZone } }); setCreating(false); await load(); }
  async function trigger(id: string) { setBusy(id); try { await runAutomation(id); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Run failed"); } finally { setBusy(""); } }
  async function toggle(item: PlatformAutomation) { await updateAutomation(item.id, { enabled: !item.enabled }); await load(); }
  return <><Header eyebrow={{ zh: "工作区运行", en: "WORKSPACE OPERATIONS" }} title={{ zh: "自动化", en: "Automations" }} subtitle={{ zh: "可追踪地运行重复工作，并保留结果和错误。", en: "Run repeatable work with visible results and errors." }} action={<button onClick={() => setCreating(true)} className="primary-button">＋ {text("新建自动化", "New automation")}</button>} /><WorkspacePage>
    {creating && <CreatePanel title={text("创建自动化", "Create automation")} onClose={() => setCreating(false)}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><label className="text-xs">{text("名称", "Name")}<input name="name" required autoFocus className="mt-1.5 min-h-11 w-full px-3" /></label><label className="text-xs">{text("工作流", "Workflow")}<select name="kind" className="mt-1.5 min-h-11 w-full px-3"><option value="job_search">{text("职位搜索闭环", "Career discovery workflow")}</option><option value="workspace_snapshot">{text("工作区快照", "Workspace snapshot")}</option></select></label><label className="text-xs">{text("职位关键词", "Job query")}<input name="query" className="mt-1.5 min-h-11 w-full px-3" placeholder="Machine Learning" /></label><label className="text-xs">{text("地区", "Location")}<select name="location" defaultValue="canada" className="mt-1.5 min-h-11 w-full px-3"><option value="canada">Canada</option><option value="us">United States</option><option value="uk">United Kingdom</option><option value="australia">Australia</option><option value="germany">Germany</option></select></label><label className="text-xs">{text("运行计划", "Schedule")}<select name="schedule" defaultValue="manual" className="mt-1.5 min-h-11 w-full px-3"><option value="manual">{text("仅手动", "Manual only")}</option><option value="daily@09:00">{text("每天 09:00", "Daily at 09:00")}</option><option value="weekly:0@09:00">{text("每周一 09:00", "Monday at 09:00")}</option><option value="hourly">{text("每小时", "Hourly")}</option></select></label><label className="text-xs">{text("最低匹配分", "Minimum match score")}<input name="min_match_score" type="number" min="0" max="100" defaultValue="60" className="mt-1.5 min-h-11 w-full px-3" /></label><label className="text-xs">{text("失败重试", "Failure retries")}<select name="max_retries" defaultValue="2" className="mt-1.5 min-h-11 w-full px-3"><option value="0">0</option><option value="1">1</option><option value="2">2</option><option value="3">3</option></select></label><label className="text-xs">{text("每次最多生成材料", "Max documents per run")}<select name="max_generate" defaultValue="1" className="mt-1.5 min-h-11 w-full px-3"><option value="1">1</option><option value="2">2</option><option value="3">3</option></select></label><label className="flex items-start gap-3 rounded-[10px] bg-[#E1EAE5] p-4 text-xs sm:col-span-2"><input name="generate_materials" type="checkbox" className="mt-0.5" /><span>{text("为达标的新职位自动生成简历和求职信。材料只进入待审核状态，不会自动投递。", "Automatically generate resume and cover letter for qualifying new jobs. Materials remain pending review and are never auto-submitted.")}</span></label><button className="primary-button justify-self-start">{text("创建", "Create")}</button></form></CreatePanel>}
    {error && <p className="rounded-[12px] bg-[#E1EAE5] p-4 text-xs">{error}</p>}
    <Section title={text("工作流", "Workflows")} eyebrow={`${items.length}`}>
      {items.length === 0 ? <EmptyState icon="catkin" title={text("还没有自动化", "No automations yet")} description={text("创建一个职位搜索闭环，从发现机会开始。", "Create a career discovery workflow to start finding opportunities.")} action={{ label: text("创建第一个", "Create the first one"), onClick: () => setCreating(true) }} /> : <div className="grid gap-4 md:grid-cols-2">{items.map((item) => <article key={item.id} className="rounded-[16px] border border-[rgba(38,51,47,0.12)] bg-[#F8FAF8] p-5"><div className="flex items-center justify-between"><StatusPill tone={item.enabled ? "brand" : "neutral"}>{item.enabled ? "Enabled" : "Paused"}</StatusPill><button onClick={() => toggle(item)} className="text-[10px] underline">{item.enabled ? text("暂停", "Pause") : text("启用", "Enable")}</button></div><h3 className="mt-4 text-sm font-medium">{item.name}</h3><p className="mt-1 text-xs text-[#52645C]">{item.kind} · {item.schedule || text("手动运行", "Manual")}</p>{item.next_run_at && <p className="mt-2 text-[10px] text-[#64736C]">{text("下次运行", "Next run")}: {new Date(item.next_run_at).toLocaleString()}</p>}<button onClick={() => trigger(item.id)} disabled={!item.enabled || busy === item.id} className="secondary-button mt-4 disabled:opacity-50">{busy === item.id ? text("运行中…", "Running…") : text("立即运行", "Run now")}</button></article>)}</div>}
    </Section>
    <Section title={text("职位结果", "Job results")} eyebrow={`${runs.length} ${text("次运行", "runs")}`}><AutomationRunHistory runs={runs} text={text} /></Section>
  </WorkspacePage></>;
}
