"use client";

import { FormEvent, useEffect, useState } from "react";
import Header from "@/components/Header";
import { BirchIcon } from "@/components/icons/BirchIcons";
import { Section, StatusPill, WorkspacePage } from "@/components/workspace/WorkspaceUI";
import { Conversation, CopilotMessage, createConversation, getConversation, listConversations, sendCopilotMessage } from "@/lib/platform-api";
import { useLanguage } from "@/lib/language-context";
import { useWorkspace } from "@/lib/workspace-context";

export default function CopilotPage() {
  const { projects, tasks, knowledge } = useWorkspace(); const { text } = useLanguage();
  const [conversations, setConversations] = useState<Conversation[]>([]); const [activeId, setActiveId] = useState(""); const [messages, setMessages] = useState<CopilotMessage[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { listConversations().then((data) => { setConversations(data.conversations); if (data.conversations[0]) setActiveId(data.conversations[0].id); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Conversations could not be loaded")); }, []);
  useEffect(() => { if (!activeId) { setMessages([]); return; } getConversation(activeId).then((data) => setMessages(data.messages)).catch((reason) => setError(reason instanceof Error ? reason.message : "Conversation could not be loaded")); }, [activeId]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const content = String(new FormData(form).get("message") ?? "").trim(); if (!content) return; setBusy(true); setError(""); try { let conversationId = activeId; if (!conversationId) { const created = await createConversation(content.slice(0, 60)); conversationId = created.conversation.id; setActiveId(conversationId); setConversations((current) => [created.conversation, ...current]); } const result = await sendCopilotMessage(conversationId, content); setMessages((current) => [...current, result.user_message, result.assistant_message]); form.reset(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Copilot could not respond"); } finally { setBusy(false); } }
  const openTasks = tasks.filter((task) => task.status === "todo").length;
  return <><Header eyebrow={{ zh: "全局智能层", en: "WORKSPACE INTELLIGENCE" }} title={{ zh: "AI 助手", en: "AI Copilot" }} subtitle={{ zh: "基于你已授权的工作区数据进行对话。", en: "Converse using only your authorized workspace data." }} action={<button onClick={async () => { const created = await createConversation(text("新对话", "New conversation")); setConversations((current) => [created.conversation, ...current]); setActiveId(created.conversation.id); }} className="secondary-button">＋ {text("新对话", "New chat")}</button>} /><WorkspacePage>
    <section className="rounded-[16px] border border-[rgba(30,26,20,0.12)] bg-[#F5EFE0] p-6"><div className="flex flex-wrap gap-2"><StatusPill tone="brand">{projects.length} {text("个项目", "projects")}</StatusPill><StatusPill tone="warning">{openTasks} {text("项待办", "open tasks")}</StatusPill><StatusPill tone="neutral">{knowledge.length} {text("条知识", "knowledge items")}</StatusPill></div></section>
    <div className="grid gap-6 lg:grid-cols-[220px_1fr]"><Section title={text("对话", "Conversations")}><div className="space-y-2">{conversations.map((item) => <button key={item.id} onClick={() => setActiveId(item.id)} className={`w-full rounded-[8px] px-3 py-2 text-left text-xs ${activeId === item.id ? "bg-[#1E1A14] text-[#F5EFE0]" : "bg-[#EBE2CC]"}`}>{item.title}</button>)}</div></Section><section className="flex min-h-[480px] flex-col rounded-[16px] border border-[rgba(30,26,20,0.12)] bg-[#F5EFE0] p-5"><div className="flex-1 space-y-4 overflow-y-auto">{messages.length === 0 && <div className="py-20 text-center"><BirchIcon name="leaf" size={35} className="mx-auto opacity-60" /><p className="mt-4 text-xs text-[#7A6A50]">{text("询问项目、任务、知识或职业申请。", "Ask about projects, tasks, knowledge, or career applications.")}</p></div>}{messages.map((message) => <article key={message.id} className={`max-w-[85%] rounded-[12px] p-4 text-sm leading-7 ${message.role === "user" ? "ml-auto bg-[#1E1A14] text-[#F5EFE0]" : "bg-[#EBE2CC] text-[#1E1A14]"}`}><p className="whitespace-pre-wrap">{message.content}</p>{message.citations && message.citations.length > 0 && <p className="mt-3 text-[9px] opacity-60">{text("参考工作区内容", "Workspace references")}: {message.citations.length}</p>}</article>)}</div>{error && <p className="my-3 rounded-[8px] bg-[#EBE2CC] p-3 text-xs">{error}</p>}<form onSubmit={submit} className="mt-4 flex gap-3 border-t border-[rgba(30,26,20,0.12)] pt-4"><textarea name="message" required rows={2} className="min-h-12 flex-1 px-3 py-2" placeholder={text("输入问题…", "Ask a question…")} /><button disabled={busy} className="primary-button self-end disabled:opacity-50">{busy ? text("思考中…", "Thinking…") : text("发送", "Send")}</button></form></section></div>
  </WorkspacePage></>;
}
